const items = [
    {
      id: '001',
      item_image: '../image/1.jpg',
      company_name: 'Carlton London',
      item_name: 'Rodium-Plated CZ Floral Studs',
      ratings: { stars: 4.5, noOfReviews: 1400 },
      current_price: 606,
      original_price: 1045,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '002',
      item_image: '../image/2.jpg',
      company_name: 'Cukoo',
      item_name: 'Women Padded Halter Neck Swimming Dress',
      ratings: { stars: 4.3, noOfReviews: 140 },
      current_price: 1507,
      original_price: 2599,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '003',
      item_image: '../image/3.jpg',
      company_name: 'Nuevosdamas',
      item_name: 'Women Red & White Printed A-Line Knee-Length Skirt',
      ratings: { stars: 4.1, noOfReviews: 2100 },
      current_price: 495,
      original_price: 1599,
      discount_percentage: 69,
      delivery_date: '10 feb 2026',
    },
    {
      id: '004',
      item_image: '../image/4.jpg',
      company_name: 'Adidas',
      item_name: 'Indian Cricket ODI Jersey',
      ratings: { stars: 5.0, noOfReviews: 1500 },
      current_price: 999,
      original_price: 999,
      discount_percentage: 0,
      delivery_date: '10 feb 2026',
    },
    {
      id: '005',
      item_image: '../image/5.jpg',
      company_name: 'Roadster',
      item_name: 'Pure Cotton T-shirt',
      ratings: { stars: 0, noOfReviews: 0 },
      current_price: 489,
      original_price: 1399,
      discount_percentage: 65,
      delivery_date: '10 feb 2026',
    },
    {
      id: '006',
      item_image: '../image/6.jpg',
      company_name: 'Nike',
      item_name: 'Sports Running Shoes',
      ratings: { stars: 4.2, noOfReviews: 980 },
      current_price: 2499,
      original_price: 4999,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
    {
      id: '007',
      item_image: '../image/7.jpg',
      company_name: 'The Indian Garage Co',
      item_name: 'Men Slim Fit Regular Shorts',
      ratings: { stars: 4.2, noOfReviews: 432 },
      current_price: 639,
      original_price: 1599,
      discount_percentage: 60,
      delivery_date: '10 feb 2026',
    },
    {
      id: '008',
      item_image: '../image/8.jpg',
      company_name: 'Nivea',
      item_name: 'Men Fresh Deodorant 150ml',
      ratings: { stars: 4.2, noOfReviews: 980 },
      current_price: 142,
      original_price: 285,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
    {
      id: '009',
      item_image: '../image/9.jpg',
      company_name: 'Sangria',
      item_name: 'Embroidered Flared Maxi Gown',
      ratings: { stars: 4.1, noOfReviews: 1324 },
      current_price: 1332,
      original_price: 4849,
      discount_percentage: 73,
      delivery_date: '10 feb 2026',
    },
    {
      id: '010',
      item_image: '../image/10.jpg',
      company_name: 'Style X Revolte',
      item_name: 'Single-Breasted Overcoat',
      ratings: { stars: 4.2, noOfReviews: 9801 },
      current_price: 1919,
      original_price: 4799,
      discount_percentage: 60,
      delivery_date: '10 feb 2026',
    },
    {
      id: '011',
      item_image: '../image/11.jpg',
      company_name: 'Include',
      item_name: 'Boys Hooded Lightweight Corduroy Cotton Tailored Jacket',
      ratings: { stars: 4.6, noOfReviews: 409 },
      current_price: 999,
      original_price: 1999,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
  ];