const items = [
    {
      id: '001',
      category: 'Women',
      item_image: '../image/1.jpg',
      company_name: 'Carlton London',
      item_name: 'Rodium-Plated CZ Floral Studs',
      ratings: { stars: 4.5, noOfReviews: 1400 },
      current_price: 606,
      original_price: 1045,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '002',
      category: 'Women',
      item_image: '../image/2.jpg',
      company_name: 'Cukoo',
      item_name: 'Women Padded Halter Neck Swimming Dress',
      ratings: { stars: 4.3, noOfReviews: 140 },
      current_price: 1507,
      original_price: 2599,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '003',
      category: 'Women',
      item_image: '../image/3.jpg',
      company_name: 'Nuevosdamas',
      item_name: 'Women Red & White Printed A-Line Knee-Length Skirt',
      ratings: { stars: 4.1, noOfReviews: 2100 },
      current_price: 495,
      original_price: 1599,
      discount_percentage: 69,
      delivery_date: '10 feb 2026',
    },
    {
      id: '004',
      category: 'Men',
      item_image: '../image/4.jpg',
      company_name: 'Adidas',
      item_name: 'Indian Cricket ODI Jersey',
      ratings: { stars: 5.0, noOfReviews: 1500 },
      current_price: 999,
      original_price: 999,
      discount_percentage: 0,
      delivery_date: '10 feb 2026',
    },
    {
      id: '005',
      category: 'Men',
      item_image: '../image/5.jpg',
      company_name: 'Roadster',
      item_name: 'Pure Cotton T-shirt',
      ratings: { stars: 0, noOfReviews: 0 },
      current_price: 489,
      original_price: 1399,
      discount_percentage: 65,
      delivery_date: '10 feb 2026',
    },
    {
      id: '006',
      category: 'Men',
      item_image: '../image/6.jpg',
      company_name: 'Nike',
      item_name: 'Sports Running Shoes',
      ratings: { stars: 4.2, noOfReviews: 980 },
      current_price: 2499,
      original_price: 4999,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
    {
      id: '007',
      category: 'Men',
      item_image: '../image/7.jpg',
      company_name: 'The Indian Garage Co',
      item_name: 'Men Slim Fit Regular Shorts',
      ratings: { stars: 4.2, noOfReviews: 432 },
      current_price: 639,
      original_price: 1599,
      discount_percentage: 60,
      delivery_date: '10 feb 2026',
    },
    {
      id: '008',
      category: 'Men',
      item_image: '../image/8.jpg',
      company_name: 'Nivea',
      item_name: 'Men Fresh Deodorant 150ml',
      ratings: { stars: 4.2, noOfReviews: 980 },
      current_price: 142,
      original_price: 285,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
    {
      id: '009',
      category: 'Women',
      item_image: '../image/9.jpg',
      company_name: 'Sangria',
      item_name: 'Embroidered Flared Maxi Gown',
      ratings: { stars: 4.1, noOfReviews: 1324 },
      current_price: 1332,
      original_price: 4849,
      discount_percentage: 73,
      delivery_date: '10 feb 2026',
    },
    {
      id: '010',
      category: 'Women',
      item_image: '../image/10.jpg',
      company_name: 'Style X Revolte',
      item_name: 'Single-Breasted Overcoat',
      ratings: { stars: 4.2, noOfReviews: 9801 },
      current_price: 1919,
      original_price: 4799,
      discount_percentage: 60,
      delivery_date: '10 feb 2026',
    },
    {
      id: '011',
      category: 'Kid',
      item_image: '../image/11.jpg',
      company_name: 'Include',
      item_name: 'Boys Hooded Lightweight Corduroy Cotton Tailored Jacket',
      ratings: { stars: 4.6, noOfReviews: 409 },
      current_price: 999,
      original_price: 1999,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
   
    {
      id: '013',
      category: 'Men',
      item_image: '../image/13.jpeg',
      company_name: 'Ralph lauren',
      item_name: 'Double Brested suit,',
      ratings: { stars: 4.3, noOfReviews: 140 },
      current_price: 1507,
      original_price: 2599,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '014',
      category: 'Men',
      item_image: '../image/14.jpg',
      company_name: 'Titan',
      item_name: 'Men Watch',
      ratings: { stars: 4.1, noOfReviews: 2100 },
      current_price: 495,
      original_price: 1599,
      discount_percentage: 69,
      delivery_date: '10 feb 2026',
    },
      
    {
      id: '012',
      category: 'Women',
      item_image: '../image/12.jpeg',
      company_name: 'Sabyasachi lehenga',
      item_name: 'Women Gown',
      ratings: { stars: 4.8, noOfReviews: 5433 },
      current_price: 4500,
      original_price: 5000,
      discount_percentage: 10,
      delivery_date: '10 feb 2026',
    },
      {
      id: '015',
      category: 'Women',
      item_image: '../image/15.jpeg',
      company_name: 'LITZO Women wear',
      item_name: 'Western One Piece',
      ratings: { stars: 4.2, noOfReviews: 2034 },
      current_price: 1584,
      original_price: 1589,
      discount_percentage: 5,
      delivery_date: '10 feb 2026',
    },
      {
      id: '016',
      category: 'Women',
      item_image: '../image/16.jpeg',
      company_name: 'Armina',
      item_name: 'Beige Kanjivaram Silk Saree',
      ratings: { stars: 4.6, noOfReviews: 6543 },
      current_price: 13500,
      original_price: 15000,
      discount_percentage: 10,
      delivery_date: '10 feb 2026',
    },
      {
      id: '017',
      category: 'Women',
      item_image: '../image/17.jpg',
      company_name: 'Titan',
      item_name: 'Women Watch',
      ratings: { stars: 4.1, noOfReviews: 2100 },
      current_price: 495,
      original_price: 1599,
      discount_percentage: 69,
      delivery_date: '10 feb 2026',
    },
      {
      id: '018',
      category: 'Kid',
      item_image: '../image/18.jpeg',
      company_name: 'Campus',
      item_name: 'Kids shoes',
      ratings: { stars: 3.8, noOfReviews: 2345 },
      current_price:1350 ,
      original_price: 1500,
      discount_percentage:10 ,
      delivery_date: '10 feb 2026',
    },
      {
      id: '019',
      category: 'Kid',
      item_image: '../image/19.jpeg',
      company_name: 'Nautinati Girls',
      item_name: 'Printed Dress',
      ratings: { stars: 4.1, noOfReviews: 2100 },
      current_price: 495,
      original_price: 1599,
      discount_percentage: 69,
      delivery_date: '10 feb 2026',
    },
    {
      id: '020',
      category: 'Kid',
      item_image: '../image/20.jpg',
      company_name: 'LITZO ',
      item_name: 'Kurta Pant',
      ratings: { stars: 4.2, noOfReviews: 2034 },
      current_price: 1584,
      original_price: 1589,
      discount_percentage: 5,
      delivery_date: '10 feb 2026',
    },

    
      {
      id: '021',
      category: 'Kid',
      item_image: '../image/21.webp',
      company_name: 'MANGO Kids',
      item_name: 'Kurta Pajama',
      ratings: { stars: 3.8, noOfReviews: 2345 },
      current_price:1350 ,
      original_price: 1500,
      discount_percentage:10 ,
      delivery_date: '10 feb 2026',
    },
 {
      id: '022',
      category: 'Kid',
      item_image: '../image/22.webp',
      company_name: 'MANGO Kids',
      item_name: 'Suit Girls',
      ratings: { stars: 3.8, noOfReviews: 2000 },
      current_price:900 ,
      original_price: 100,
      discount_percentage:10 ,
      delivery_date: '10 feb 2026',
    },
     
     {
      id: '023',
      category: 'Beauty',
      item_image: '../image/23.jpeg',
      company_name: 'Huda Beauty',
      item_name: 'Makeup Product',
      ratings: { stars: 4.5, noOfReviews: 1400 },
      current_price: 606,
      original_price: 1045,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '024',
      category: 'Beauty',
      item_image: '../image/24.jpeg',
      company_name: 'LAKME',
      item_name: 'Skin-Care Product',
      ratings: { stars: 4.3, noOfReviews: 140 },
      current_price: 1507,
      original_price: 2599,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
    {
      id: '025',
      category: 'Beauty',
      item_image: '../image/25.jpeg',
      company_name: 'LAKME',
      item_name: 'Beauty Product',
      ratings: { stars: 4.6, noOfReviews: 409 },
      current_price: 999,
      original_price: 1999,
      discount_percentage: 50,
      delivery_date: '10 feb 2026',
    },
   
    {
      id: '026',
      category: 'Beauty',
      item_image: '../image/26.jpg',
      company_name: 'SWISS BEAUTY',
      item_name: 'Lipstick',
      ratings: { stars: 4.3, noOfReviews: 140 },
      current_price: 1507,
      original_price: 2599,
      discount_percentage: 42,
      delivery_date: '10 feb 2026',
    },
{
      id: '027',
      category: 'Home',
      item_image: '../image/27.jpg',
      company_name: 'SQUREL',
      item_name: 'Sofa Set',
      ratings: { stars: 5.0, noOfReviews: 15000 },
      current_price: 32000,
      original_price: 32000,
      discount_percentage: 0,
      delivery_date: '10 feb 2026',
    },
    {
      id: '028',
      category: 'Home',
      item_image: '../image/28.jpg',
      company_name: 'Kuber Floor',
      item_name: 'Cotton Mop',
      ratings: { stars: 3.4, noOfReviews: 3006 },
      current_price: 489,
      original_price: 1399,
      discount_percentage: 65,
      delivery_date: '10 feb 2026',
    },
    {
      id: '029',
      category: 'Home',
      item_image: '../image/29.jpeg',
      company_name: 'LAGET',
      item_name: 'Soap Dispenser',
      ratings: { stars: 4.2, noOfReviews: 980 },
      current_price: 350,
      original_price: 500,
      discount_percentage: 30,
      delivery_date: '10 feb 2026',
    },
    {
      id: '030',
      category: 'Home',
      item_image: '../image/30.jpeg',
      company_name: 'SWAPKART',
      item_name: 'Layer Soap Dispenser',
      ratings: { stars: 4.2, noOfReviews: 432 },
      current_price: 639,
      original_price: 1599,
      discount_percentage: 60,
      delivery_date: '10 feb 2026',
    },
  ];